export enum Languages {
  NODE = 'node',
  PYTHON = 'python',
  CPP = 'cpp',
  C = 'c',
  RUBY = 'ruby',
  JAVA = 'java',
  RUST = 'rust',
  HASKELL = 'haskell',
  ELIXIR = 'elixir',
  GOLANG = 'golang',
  PERL = 'perl',
  SWIFT = 'swift',
  DART = 'dart',
}
